### PR TITLE
Add support for SET params with array

### PR DESCRIPTION
**Pull request by mad**
#236

Signed-off-by: Pavel Ershov <owner.mad.epa@gmail.com>

### CODE REVIEW

**Comment by dwitry** [comment]
Hello @mad,

this PR allows to produce translation for setting collections in properties. However in my case it still fails on JanusGraph with `Property value [[1, 2]] is of type class java.util.ArrayList is not supported`.

Have you managed to configure it on JanusGraph side? If so, could you please share configuration.

**Comment by mad** [comment]
I defined property with String[].class datatype, and StringArraySerializer do conversion from Iterable to String[]

**Comment by dwitry** [comment]
Hello @mad,

could you please share your JanusGraph configuration?

```
attributes.custom.attribute1.attribute-class = java.lang.String[].class
attributes.custom.attribute1.serializer-class = org.janusgraph.graphdb.database.serialize.attribute.StringArraySerializer
```

Fails on startup in my case.

**Comment by mad** [comment]
Hello @dwitry 

```
class Scratch {
    public static void main(String[] args) {
        JanusGraph graph = JanusGraphFactory.open("inmemory");
        JanusGraphManagement mgmt = graph.openManagement();
        mgmt.makePropertyKey("P").dataType(String[].class).make();
        mgmt.commit();

        GraphTraversalSource traversal = graph.traversal();

        traversal.addV("A").property("P", Lists.newArrayList("a", "b")).iterate();
        Assert.assertArrayEquals(new String[] { "a", "b" }, (String[]) traversal.V().values("P").next());
        graph.close();
    }
}
```

**Comment by dwitry** [comment]
* It appears to me that this feature requires `ArrayList<String>` serialization not `String[]`, @mad please correct if I'm wrong
* Tested with https://github.com/pluradj/janusgraph-attribute-serializer
* [Merged](https://github.com/opencypher/cypher-for-gremlin/commit/424827a3447ff3c0c58170b4e80e035e5735c897) to `tinkerpop334`
* Resolves #236

**Comment by mad** [comment]
@dwitry 

No, default [StringArraySerializer](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/attribute/StringArraySerializer.java) it is enough for handle String[] and all Iterable<String> see [StandardSerializer](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/StandardSerializer.java#L105) and [ArraySerializer.convertInternal](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-core/src/main/java/org/janusgraph/graphdb/database/serialize/attribute/ArraySerializer.java#L34)

But if we defined property with ArrayList data type we need to register special serializer that provided by https://github.com/pluradj/janusgraph-attribute-serializer

**Pull request merged**
