### PR TITLE
Add custom functions round, trim

### PR DESCRIPTION
**Pull request by mad**
Add round/trim custom functions

https://github.com/opencypher/cypher-for-gremlin/issues/225

### CODE REVIEW

**Comment by dwitry** [comment]
@mad, thank you for your contribution! We will merge this. 

To make openCypher able to accept this and other pull requests, could you please [confirm your agreement](https://github.com/opencypher/cypher-for-gremlin/blob/master/CONTRIBUTING.md) to the terms of the oCCA? 

It is simple process - basically you need to send [pdf](https://s3.amazonaws.com/artifacts.opencypher.org/openCypher+Contributor+Agreement.pdf) with your credentials to email provided, then `git commit --signoff`.

**Comment by mad** [comment]
Ok, I'm apply and send this agreement

**Comment by dwitry** [comment]
@mad, thank you for signing oCCA. All commits in this repository are signed. Would you mind to sign off your commit (`git commit --amend --signoff`) and force push it to this branch?

**Comment by mad** [comment]
done

**Comment by dwitry** [comment]
Rebased with master, added couple additional tests. 
This resolves #225.

**Pull request merged**
